"use strict";
const assert=require("node:assert/strict"),test=require("node:test");
const {dismissReleaseNotes,getPendingReleaseNotes,openReleaseNotesDetails,testModeRequested}=require("../electron/release-experience.cjs");
function memoryFs(initial=null){let stored=initial;return{async readFile(){if(stored==null)throw Object.assign(new Error("missing"),{code:"ENOENT"});return stored},async mkdir(){},async writeFile(_f,v){stored=v},value:()=>stored==null?null:JSON.parse(stored)}}
const appImpl={getVersion:()=>"3.2.5",getPath:()=>"/tmp/nexora-release-test"};
test("post-update summary is returned to the renderer on first 3.2.5 launch",async()=>{const fsImpl=memoryFs();const notes=await getPendingReleaseNotes({appImpl,fsImpl});assert.equal(notes.version,"3.2.5");assert.match(notes.title,/3\.2\.5/);assert.ok(notes.highlights.length>=4);assert.equal(fsImpl.value().pendingNotesVersion,"3.2.5")});
test("renderer dismissal is persisted only when do-not-show-again is selected",async()=>{const fsImpl=memoryFs(JSON.stringify({lastVersion:"3.2.4"}));await getPendingReleaseNotes({appImpl,fsImpl});await dismissReleaseNotes({appImpl,fsImpl,version:"3.2.5",dontShowAgain:true});assert.equal(await getPendingReleaseNotes({appImpl,fsImpl}),null);assert.equal(fsImpl.value().dismissedNotesVersion,"3.2.5")});
test("details opens the exact official release tag",async()=>{let opened=null;const result=await openReleaseNotesDetails({appImpl,shellImpl:{openExternal:async url=>{opened=url}},version:"3.2.5"});assert.equal(result.opened,true);assert.equal(opened,"https://github.com/Onmaynec/Nexora/releases/tag/v3.2.5")});
test("test mode accepts command line and environment switches",()=>{const previous=process.env.NEXORA_CLIENT_TEST_MODE;delete process.env.NEXORA_CLIENT_TEST_MODE;assert.equal(testModeRequested(["electron","app","--test-mode"]),true);assert.equal(testModeRequested(["electron","app"]),false);process.env.NEXORA_CLIENT_TEST_MODE="1";assert.equal(testModeRequested(["electron","app"]),true);if(previous==null)delete process.env.NEXORA_CLIENT_TEST_MODE;else process.env.NEXORA_CLIENT_TEST_MODE=previous});
